### ISSUE TITLE
无法正常显示窗口缩略图

### ISSUE THREAD

**Issue by wangwenx190** [KngStr/Inno-All-in-One-Setup#5]
如题，inno打包的安装程序都无法正常显示窗口缩略图，Windows好像把这个功能叫做Aero Peek。我觉得这是inno自身的bug。

**Comment by KngStr** [comment]
对的，这个是Inno官方的bug

**Comment by wangwenx190** [comment]
这个bug已经遗留好久了，一直都不见要修复的迹象。您知道怎么联系inno作者吗？我想亲自给作者提一下。我star了inno的repo，但作者没有开issues功能。

**Comment by KngStr** [comment]
去Inno官网，邮件列表里面提
