### ISSUE TITLE
使用示例报错

### ISSUE THREAD

**Issue by AdminHcat** [KngStr/Inno-All-in-One-Setup#9]
![image](https://user-images.githubusercontent.com/50044729/179405878-cf874edd-9c19-4ed1-ad11-d096a3032a74.png)

**Comment by pzhlkj6612** [comment]
你好！根据代码：

https://github.com/KngStr/Inno-All-in-One-Setup/blob/ade4664ddeab106a07084aef7f63e604d1106c49/Include/ISPP/InstFiles.ish#L182-L187

```InstFiles``` 有三个参数，分别为 ```Dir``` ，```Mask``` 和 ```Flags``` ，你缺少的正是 ```Flags``` 。程序中有预设的 flags ，所以你可以试着写一个空字符串，也就是：

```c
#expr InstFiles("D:\Users", "*.*", "")
```

**Comment by AdminHcat** [comment]
已解决，请更新示例 #10
